alter table public.challenges drop constraint if exists challenges_track_check;

insert into public.challenges (
  id,
  slug,
  title,
  track,
  difficulty,
  estimated_minutes,
  context,
  prompt,
  rubric_notes,
  tags
) values
(
  '11111111-1111-4111-8111-111111111111',
  'recursion-and-self-knowledge',
  'The Mirror Room',
  'identity',
  'Beginner',
  18,
  'You enter a room with three mirrors. The first shows your face, the second shows a recording of how you reacted to the first, and the third shows a stranger accurately describing the motives behind that reaction.',
  'Which mirror, if any, gives you the best knowledge of yourself? Argue whether self-knowledge depends more on first-person awareness, observed behavior, or interpretation by others.',
  array['Choose a clear account of what counts as self-knowledge.', 'Compare at least two sources of self-understanding.', 'Address how a person can be mistaken about their own motives.'],
  array['self-knowledge', 'reflection', 'identity']
),
(
  '22222222-2222-4222-8222-222222222222',
  'the-last-seat',
  'The Last Seat',
  'ethics',
  'Intermediate',
  22,
  'A rescue shuttle has one seat left. One candidate is likely to save many people later, one is the person who fixed the shuttle, and one was selected by a fair lottery before anyone knew their identities.',
  'Who should receive the last seat, and what makes that reason morally relevant? Defend a rule for choosing that you would still accept if you did not know which candidate you would be.',
  array['Identify the moral principle behind the choice.', 'Consider fairness, gratitude, and future consequences.', 'Answer an objection from one of the rejected candidates.'],
  array['triage', 'fairness', 'responsibility']
),
(
  '33333333-3333-4333-8333-333333333333',
  'the-memory-archive',
  'The Memory Archive',
  'identity',
  'Intermediate',
  24,
  'A patient can restore every lost memory from a perfect archive, but the archive also includes memories from a different person who lived a better life and consented to donate them.',
  'If the patient accepts the donated memories, do they become partly the donor, remain wholly themselves, or become someone new? Argue for a view of personal identity that can handle mixed memory.',
  array['Explain whether memory is evidence of identity or part of identity.', 'Distinguish psychological continuity from ownership of experience.', 'Consider whether consent changes the identity question.'],
  array['memory', 'personhood', 'continuity']
),
(
  '44444444-4444-4444-8444-444444444444',
  'promise-to-a-copy',
  'Promise to a Copy',
  'identity',
  'Advanced',
  28,
  'You promise to help a friend tomorrow. Overnight, a perfect copy of your friend appears, with the same memories and the same expectation that you will keep the promise.',
  'Do you owe the promise to the original, the copy, both, or neither until you can tell them apart? Defend an answer that explains what promises attach to.',
  array['Clarify whether promises attach to bodies, persons, histories, or relationships.', 'Address the possibility of duplicated claims.', 'Explain what would make one claim stronger than another.'],
  array['copies', 'promises', 'obligation']
),
(
  '55555555-5555-4555-8555-555555555555',
  'the-harmless-lie-machine',
  'The Harmless Lie Machine',
  'ethics',
  'Beginner',
  18,
  'A machine can tell each person one false but comforting sentence per day. The lies are designed never to affect decisions, only mood, and no one can discover that the machine lies.',
  'Would using the machine be morally wrong if it caused no practical harm? Argue whether truth matters only because of consequences or also because of respect for persons.',
  array['State whether harmless deception can still be wrong.', 'Explain the relation between truth, autonomy, and comfort.', 'Consider why someone might rationally prefer the pleasant lie.'],
  array['truth', 'harm', 'trust']
),
(
  '66666666-6666-4666-8666-666666666666',
  'the-fair-lottery',
  'The Fair Lottery',
  'ethics',
  'Intermediate',
  24,
  'A school must award one scholarship. The finalists are equally qualified, but one has overcome severe hardship, one will do the most public good, and one was randomly selected by a transparent lottery.',
  'When reasons run out or conflict, is a lottery the fairest solution or an abdication of judgment? Defend a standard for when randomness is morally appropriate.',
  array['Separate equality of procedure from equality of outcome.', 'Explain whether hardship or future benefit should break the tie.', 'Address the worry that lotteries hide responsibility.'],
  array['luck', 'desert', 'equality']
),
(
  '77777777-7777-4777-8777-777777777777',
  'the-sealed-testimony',
  'The Sealed Testimony',
  'knowledge',
  'Intermediate',
  24,
  'Ten reliable witnesses independently write down what happened in a sealed room. You cannot inspect the room, but all ten reports agree. Later, you learn the witnesses share the same teacher and vocabulary.',
  'How much should agreement among witnesses count as knowledge when their background may have shaped what they noticed? Argue for a view of testimony that avoids both cynicism and blind trust.',
  array['Explain why independent agreement can be evidence.', 'Consider how shared background can reduce independence.', 'Give a standard for rational trust in testimony.'],
  array['testimony', 'evidence', 'trust']
),
(
  '88888888-8888-4888-8888-888888888888',
  'the-perfect-map',
  'The Perfect Map',
  'knowledge',
  'Advanced',
  30,
  'A kingdom builds a map so detailed that every object, person, and motion appears on it in real time. The map is too large for any citizen to understand all at once.',
  'Can a representation be perfectly accurate and still fail to give understanding? Argue what must be added to accurate information for it to become knowledge.',
  array['Distinguish accuracy from intelligibility.', 'Explain the role of selection, scale, or purpose in understanding.', 'Address whether simplification can improve knowledge.'],
  array['representation', 'reality', 'understanding']
),
(
  '99999999-9999-4999-8999-999999999999',
  'the-forgotten-crime',
  'The Forgotten Crime',
  'identity',
  'Advanced',
  30,
  'A person committed a serious crime twenty years ago, then suffered an accident that erased all memory of it and permanently changed their character. The evidence is certain.',
  'Is punishment still justified when the guilty person no longer remembers the act and no longer has the character that produced it? Defend a view of responsibility across psychological change.',
  array['Clarify whether responsibility requires memory, character continuity, or bodily continuity.', 'Consider victims, deterrence, and desert separately.', 'Answer the objection that forgetting cannot erase guilt.'],
  array['responsibility', 'memory', 'punishment']
),
(
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'the-prediction-letter',
  'The Prediction Letter',
  'knowledge',
  'Beginner',
  20,
  'A sealed letter on your desk accurately predicts every choice you made yesterday. It also contains a prediction for what you will do next, but you can decide whether to open it.',
  'Would reading the prediction threaten your freedom, reveal a limit that was already there, or change nothing important? Argue what this case shows about choice and foreknowledge.',
  array['State what kind of freedom is at issue.', 'Explain whether prediction causes, reveals, or merely describes action.', 'Consider why the option to open the letter matters.'],
  array['free-will', 'prediction', 'choice']
),
(
  'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  'borrowed-pain',
  'Borrowed Pain',
  'ethics',
  'Intermediate',
  23,
  'A device lets healthy volunteers experience one hour of a patient''s pain. The experience cannot heal the patient, but it may make policy makers more compassionate.',
  'Is borrowing another person''s pain morally valuable, voyeuristic, or both? Argue whether empathy produced by simulation deserves moral authority.',
  array['Distinguish understanding suffering from using suffering.', 'Consider consent and the limits of simulated experience.', 'Explain whether empathy should guide policy.'],
  array['empathy', 'suffering', 'consent']
),
(
  'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
  'the-private-language-app',
  'The Private Language App',
  'knowledge',
  'Advanced',
  28,
  'An app lets you create words for inner sensations that no one else can observe or correct. Over time, you rely on the app''s labels to make decisions about your feelings.',
  'Can a word have stable meaning if only one person can ever check its use? Argue whether private experience needs public criteria to become knowledge.',
  array['Explain what makes a word meaningful rather than merely habitual.', 'Consider whether inner experience can be checked by memory alone.', 'Address why public correction might matter for self-knowledge.'],
  array['language', 'meaning', 'privacy']
),
(
  'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
  'marys-room',
  'Mary''s Room',
  'knowledge',
  'Intermediate',
  25,
  'A scientist knows every physical fact about color vision but has lived her entire life in a black-and-white room. The day she steps outside and sees a red rose for the first time, she exclaims, "So that is what red looks like."',
  'Did Mary learn something new, or only gain a new way of accessing facts she already knew? Argue whether physical information can ever capture what an experience is like.',
  array['Distinguish knowing facts from knowing what an experience is like.', 'Consider whether Mary gains new information or new abilities.', 'Address the physicalist reply that all facts were already known.'],
  array['consciousness', 'qualia', 'physicalism']
),
(
  'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
  'the-two-drivers',
  'The Two Drivers',
  'ethics',
  'Intermediate',
  22,
  'Two equally careful drivers both run a red light by accident. One crosses an empty intersection; the other hits a child who ran into the road. The law punishes them very differently.',
  'Should moral blame depend on outcomes the driver could not control? Argue whether we are responsible only for what we intend or also for what our actions cause.',
  array['Separate responsibility for intentions from responsibility for results.', 'Consider whether luck should affect moral judgment.', 'Address the intuition that the driver who hit the child owes something more.'],
  array['moral-luck', 'responsibility', 'blame']
),
(
  'ffffffff-ffff-4fff-8fff-ffffffffffff',
  'the-experience-machine',
  'The Experience Machine',
  'ethics',
  'Beginner',
  18,
  'A machine can give you any experience you desire: writing a great novel, making a friend, climbing a mountain. Once plugged in, you will not know you are in the machine, and the experiences will feel completely real.',
  'Would you plug in for life? Argue whether a life of pleasant illusions is as good as a life of real achievements and real relationships.',
  array['Identify what matters besides pleasant experience.', 'Consider whether authenticity has independent value.', 'Address the reply that subjective experience is all that matters.'],
  array['well-being', 'authenticity', 'hedonism']
),
(
  '10101010-1010-4101-8101-101010101010',
  'the-veil-of-ignorance',
  'Behind the Veil',
  'ethics',
  'Advanced',
  30,
  'You must design the rules of a society without knowing whether you will be born rich or poor, talented or disabled, in a majority or a minority. You will live your whole life under the rules you choose.',
  'What principles of justice would you choose from behind this veil of ignorance? Defend a set of rules that you would accept no matter who you turned out to be.',
  array['Explain why ignorance of one''s position makes the choice fair.', 'Consider whether the rules should maximize the worst-off position.', 'Address the objection that the veil ignores real-world inequalities.'],
  array['justice', 'fairness', 'rawls']
),
(
  '20202020-2020-4202-8202-202020202020',
  'the-bridge-and-the-five',
  'The Bridge',
  'ethics',
  'Beginner',
  18,
  'A runaway trolley will kill five workers on the track ahead. You stand on a bridge above the track next to a large stranger. Pushing the stranger onto the track would stop the trolley and save the five.',
  'Is it morally permissible to push the stranger? Argue whether there is a morally relevant difference between diverting a threat and using a person as a means to stop it.',
  array['Distinguish doing harm from allowing harm.', 'Consider whether using a person as a means is always wrong.', 'Address the objection that five lives outweigh one.'],
  array['trolley-problem', 'means-and-ends', 'sacrifice']
),
(
  '30303030-3030-4303-8303-303030303030',
  'the-simulation-hypothesis',
  'The Simulation',
  'knowledge',
  'Intermediate',
  24,
  'A supercomputer could simulate an entire world so perfectly that its inhabitants could never detect the simulation from the inside. You have no way to prove you are not in such a simulation right now.',
  'If you cannot rule out the simulation hypothesis, do you know anything about the external world? Argue for a standard of knowledge that can handle radical skeptical scenarios.',
  array['Explain what it takes to know something rather than merely believe it.', 'Consider whether the possibility of error defeats all knowledge claims.', 'Address the reply that knowledge does not require absolute certainty.'],
  array['skepticism', 'certainty', 'simulation']
),
(
  '40404040-4040-4404-8404-404040404040',
  'the-ship-of-theseus',
  'The Restored Ship',
  'identity',
  'Beginner',
  20,
  'A ship has every plank replaced one by one over many years. Meanwhile, someone collects all the discarded planks and reconstructs the original ship. Two ships now exist.',
  'Which ship, if either, is the original? Argue for a criterion of identity through change that can handle gradual replacement and reassembly.',
  array['Consider whether identity depends on material continuity, form, or history.', 'Address the possibility that both or neither ship is the original.', 'Explain what makes your criterion better than the alternatives.'],
  array['identity', 'change', 'continuity']
),
(
  '50505050-5050-4505-8505-505050505050',
  'the-chinese-room',
  'The Chinese Room',
  'knowledge',
  'Advanced',
  28,
  'A person who knows no Chinese sits in a room with a rulebook that tells them how to respond to Chinese characters slipped under the door. To people outside, the room appears to understand Chinese perfectly.',
  'Does the room understand Chinese? Argue whether following syntactic rules can ever produce genuine understanding or whether meaning requires something more.',
  array['Distinguish simulating understanding from actually understanding.', 'Consider whether a system as a whole can understand even if its parts do not.', 'Address the reply that the person plus rulebook plus room together understand.'],
  array['artificial-intelligence', 'understanding', 'syntax']
),
(
  '60606060-6060-4606-8606-606060606060',
  'the-prisoners-dilemma',
  'The Shared Cell',
  'ethics',
  'Intermediate',
  22,
  'Two suspects are held in separate cells. If both stay silent, each gets one year. If one confesses and the other stays silent, the confessor goes free and the silent one gets ten years. If both confess, each gets five years.',
  'What should a rational person do, and what should a moral person do? Argue whether rationality and morality can conflict, and if so, which should prevail.',
  array['Explain the difference between individual and collective rationality.', 'Consider whether promises or trust can resolve the conflict.', 'Address the objection that morality is just enlightened self-interest.'],
  array['cooperation', 'rationality', 'trust']
),
(
  '70707070-7070-4707-8707-707070707070',
  'the-inverted-spectrum',
  'The Inverted World',
  'knowledge',
  'Intermediate',
  24,
  'You and a friend use the same color words and agree on every color judgment. But when you see what you call red, your friend has the inner experience you would call green, and vice versa.',
  'Could this inversion go undetected? Argue whether the private character of experience matters for knowledge, communication, or the meaning of color words.',
  array['Consider whether shared behavior guarantees shared experience.', 'Explain what role inner experience plays in the meaning of color terms.', 'Address the reply that inversion is impossible given shared biology.'],
  array['qualia', 'meaning', 'consciousness']
),
(
  '80808080-8080-4808-8808-808080808080',
  'the-state-of-nature',
  'Before the Law',
  'ethics',
  'Advanced',
  30,
  'Imagine a world with no government, no laws, and no enforcement. Everyone is free to do as they please, but no one is safe from the ambitions of others. Some argue this is a state of war; others call it a state of perfect freedom.',
  'Would people in such a state have moral obligations to each other, or would morality only begin with the creation of political authority? Defend a view of the relationship between morality and government.',
  array['Consider whether moral duties exist independently of political institutions.', 'Address whether security is a precondition for morality or a product of it.', 'Explain what, if anything, binds people together before any law exists.'],
  array['social-contract', 'authority', 'obligation']
),
(
  '90909090-9090-4909-8909-909090909090',
  'the-lucky-belief',
  'The Lucky Guess',
  'knowledge',
  'Beginner',
  20,
  'You glance at a broken clock that happens to show the correct time. You form the belief that it is 3:15, and it is indeed 3:15. Your belief is true and you have a reason for holding it.',
  'Do you know what time it is? Argue for conditions on knowledge that can distinguish a lucky true belief from genuine knowledge.',
  array['Explain why true belief with a reason may still fall short of knowledge.', 'Consider what connection must exist between a belief and the fact that makes it true.', 'Address the objection that your reason was good enough even if the clock was broken.'],
  array['gettier', 'justification', 'truth']
)
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  track = excluded.track,
  difficulty = excluded.difficulty,
  estimated_minutes = excluded.estimated_minutes,
  context = excluded.context,
  prompt = excluded.prompt,
  rubric_notes = excluded.rubric_notes,
  tags = excluded.tags;

alter table public.challenges
  add constraint challenges_track_check
  check (track in ('identity', 'ethics', 'knowledge'))
  not valid;
